config/routes.rb
Rails.application.routes.draw do

  get 'knights', to: 'knights#index', as: 'knights'
  get 'knights/new', to: 'knights#new', as: 'new_knight'
  post 'knights', to: 'knights#create'
  get 'knights/:id', to: 'knights#show', as: 'knight'
  get 'knights/:id/edit', to: 'knights#edit', as: 'edit_knight'
  patch 'knights/:id', to: 'knights#update'
  delete 'knights/:id', to: 'knights#destroy'

  get '/knights/:knight_id/apprentices', to: 'apprentices#index_for_knight', as: 'knight_apprentices'
  get '/knights/:knight_id/apprentices/new', to: 'apprentices#new', as: 'new_knight_apprentice'
  post '/knights/:knight_id/apprentices', to: 'apprentices#create'
  

  get 'apprentices', to: 'apprentices#index', as: 'apprentices'
  get 'apprentices/new', to: 'apprentices#new', as: 'new_apprentice'
  post 'apprentices', to: 'apprentices#create'
  get 'apprentices/:id', to: 'apprentices#show', as: 'apprentice'
  get 'apprentices/:id/edit', to: 'apprentices#edit', as: 'edit_apprentice'
  patch 'apprentices/:id', to: 'apprentices#update'
  delete 'apprentices/:id', to: 'apprentices#destroy'

  # Define root 
  root 'knights#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apprentice.rb
class Apprentice < ApplicationRecord
  belongs_to :knight
  validates :name, presence: true
end

app/models/knight.rb
class Knight < ApplicationRecord
    has_many :apprentices, dependent: :destroy
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apprentices_controller.rb
class ApprenticesController < ApplicationController
  def index
    @apprentices = Apprentice.where(is_knighted: true)
  end

  def new
    @knight = Knight.find(params[:knight_id])
    @apprentiece = @knight.apprentices.build
  end

  def create
    @knight = Knight.find(params[:knight_id])
    @apprentice = @knight.apprentices.build(apprentice_params)
    if @apprentice.save
      redirect_to knight_apprentices_path(@knight)
    else
      render :new
    end
  end

  def show
    @apprentice = Apprentice.find(params[:id])
  end

  def edit
    @apprentice = Apprentice.find(params[:id])
  end

  def index_for_knight
    @knight = Knight.find(params[:knight_id])
    @apprentices = @knight.apprentices
  end

  def update
    @apprentice = Apprentice.find(params[:id])
    if @apprentice.update(apprentice_params)
      redirect_to apprentice_path(@apprentice)
    else
      render :edit
    end
  end

  private

  def apprentice_params
    params.require(:apprentice).permit(:name, :is_knighted, :age, :knight_id)
  end
end

app/controllers/knights_controller.rb
class KnightsController < ApplicationController
  def index
    @knights = Knight.order(created_at: :desc)
  end

  def new
    @knight = Knight.new
  end

  def create
    @knight = Knight.new(knight_params)
    if @knight.save
      redirect_to knights_path
    else
      render :new
    end
  end

  def show
    @knight = Knight.find(params[:id])
  end

  def edit
    @knight = Knight.find(params[:id])
  end

  def update
    @knight = Knight.find(params[:id])
    if @knight.update(knight_params)
      redirect_to knight_path(@knight)
    else
      render :edit
    end
  end


  private

  def knight_params
    params.require(:knight).permit(:name, :is_active, :number_of_quests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apprentices_helper.rb
module ApprenticesHelper
end

app/helpers/knights_helper.rb
module KnightsHelper
end

app/views/apprentices/edit.html.erb
<h1>Edit Apprentice</h1>

<%= form_with(model: @apprentice, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :is_knighted %>
    <%= form.check_box :is_knighted %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit 'Update Apprentice' %>
  </div>
<% end %>

<%= link_to 'Back to Apprentice', apprentice_path(@apprentice) %>
<%= link_to 'Back to Knights', knights_path %>

app/views/apprentices/index.html.erb
<h1>Apprentices of <%= @knight.name %></h1>
<ul>
  <% @apprentices.each do |apprentice| %>
    <li>
      <%= link_to apprentice.name, apprentice_path(apprentice) %><br>
      Knighted: <%= apprentice.is_knighted %><br>
      Age: <%= apprentice.age %>
    </li>
  <% end %>
</ul>

app/views/apprentices/index_for_knight.html.erb
<h1>Apprentices of <%= @knight.name %></h1>
<p><%= link_to 'Create Apprentice', new_knight_apprentice_path(@knight) %></p>
<ul>
  <% @apprentices.each do |apprentice| %>
    <li>
      <%= link_to apprentice.name, apprentice_path(apprentice) %><br>
      Knighted: <%= apprentice.is_knighted %><br>
      Age: <%= apprentice.age %>
    </li>
  <% end %>
</ul>
<%= link_to 'Back to Knights', knights_path %>

app/views/apprentices/new.html.erb
<h1>New Apprentice for <%= @knight.name %></h1>

<%= form_with(model: [@knight, @apprentice], local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :is_knighted %>
    <%= form.check_box :is_knighted %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit 'Create Apprentice' %>
  </div>
<% end %>

<%= link_to 'Back to Apprentices', knight_apprentices_path(@knight) %>

app/views/apprentices/show.html.erb
<h1><%= @apprentice.name %></h1>
<p>Knighted: <%= @apprentice.is_knighted %></p>
<p>Age: <%= @apprentice.age %></p>
<p><%= link_to "Update Apprentice", edit_apprentice_path(@apprentice) %></p>
<%= link_to 'Back to Apprentices', apprentices_path %>
<%= link_to 'Back to Knights', knights_path %>

app/views/knights/edit.html.erb
<h1>Edit Knight</h1>

<%= form_with(model: @knight, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :is_active %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.label :number_of_quests %>
    <%= form.number_field :number_of_quests %>
  </div>

  <div>
    <%= form.submit 'Update Knight' %>
  </div>
<% end %>

<%= link_to 'Back to Knights', knights_path %>
<%= link_to 'Back to Knight', knight_path(@knight) %>

app/views/knights/index.html.erb
<h1>Knights</h1>
<p><%= link_to "New Knight", new_knight_path %></p>
<ul>
  <% @knights.each do |knight| %>
    <li>
    <%= link_to knight.name, knight_path(knight) %> - Created at: <%= knight.created_at.strftime("%B %d, %Y %H:%M") %>
    </li>
  <% end %>
</ul>

app/views/knights/new.html.erb
<h1>New Knight</h1>

<%= form_with(model: @knight, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :is_active %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.label :number_of_quests %>
    <%= form.number_field :number_of_quests %>
  </div>

  <div>
    <%= form.submit 'Create Knight' %>
  </div>
<% end %>

<%= link_to 'Back to Knights', knights_path %>

app/views/knights/show.html.erb
<h1><%= @knight.name %></h1>
<p>Active: <%= @knight.is_active %></p>
<p>Number of Quests: <%= @knight.number_of_quests %></p>
<p>Number of Apprentices: <%= @knight.apprentices.count %></p>
<p><%= link_to "View Apprentices", knight_apprentices_path(@knight) %></p>
<p><%= link_to "Update Knight", edit_knight_path(@knight) %></p>
<%= link_to 'Back to Knights', knights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnightsApprenticesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Knights Index', knights_path %> |
        <%= link_to 'Apprentices Index', apprentices_path %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>